### PR TITLE
Static credential provider

### PR DESCRIPTION
**Pull request by stsatlantis**
Add static credential provider based on provided config values.

### CODE REVIEW

**Comment by stsatlantis** [comment]
@alonsodomin If you accept this change can you please release it?

**Comment by alonsodomin** [comment]
@stsatlantis I'll try to cut a release in the next 24 hours

**Comment by stsatlantis** [comment]
@alonsodomin Thank you so much and thanks for the superquick response :)

**Comment by alonsodomin** [comment]
@stsatlantis Release 1.1.5 has been published into Maven Central, it may take a while until it gets mirrored everywhere though.

**Comment by stsatlantis** [comment]
@alonsodomin Thank you. :)

**Pull request merged**
